-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = (SELECT MAX(C.LENGTH)
                  FROM FISH_INFO AS C
                  WHERE C.FISH_TYPE = A.FISH_TYPE
                  GROUP BY C.FISH_TYPE)
# AND LENGTH IS NOT NULL
ORDER BY A.ID ASC